# Generated by Django 3.2.7 on 2021-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0002_auto_20210920_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
