# Generated by Django 3.2.7 on 2021-09-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0005_auto_20210921_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIad',
            new_name='API',
        ),
    ]
