# Generated by Django 3.2.7 on 2021-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0006_rename_apiad_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='desc_larga',
            new_name='agente',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='descripcion',
            new_name='secretaria',
        ),
        migrations.RemoveField(
            model_name='api',
            name='importe',
        ),
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
