# Generated by Django 3.2.7 on 2021-09-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0009_auto_20210921_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='agente',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='api',
            name='secretaria',
            field=models.CharField(max_length=800),
        ),
    ]
