# Generated by Django 3.2.7 on 2021-09-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0010_auto_20210921_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API',
            new_name='APIg',
        ),
    ]
