# Generated by Django 3.2.7 on 2021-09-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0011_rename_api_apig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIg',
            new_name='APIa',
        ),
    ]
