# Generated by Django 3.2.7 on 2021-09-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0012_rename_apig_apia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIa',
            new_name='API',
        ),
    ]
