# Generated by Django 3.2.7 on 2021-09-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0013_rename_apia_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='agente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='api',
            name='secretaria',
            field=models.CharField(max_length=100),
        ),
    ]
