# Generated by Django 3.2.7 on 2021-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0014_auto_20210921_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='legajo',
            field=models.IntegerField(),
        ),
    ]
