# Generated by Django 3.2.7 on 2021-09-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIg', '0015_alter_api_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='legajo',
            field=models.FloatField(),
        ),
    ]
